name: Tailsman Validation
on:
  pull_request:
    branches: [main]

jobs:
  Tailsman_Scan:
    runs-on: kubecli
    container:
      image: "dshivakumar/talisman:root"
    permissions:
      pull-requests: write 
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4.2.2
      - name: Run Tailsman
        id: tailsman
        run: |
          set +e
          tailsman --scan > tailsman_output.txt 2>&1
          echo "exit_code=$?" >> $GITHUB_OUTPUT
        continue-on-error: true
      - name: Update PR Comments
        if: steps.tailsman.outputs.exit_code != 0
        run: | 
          echo "Secrets Detected By Tailsman: "
          cat tailsman_output.txt 
          COMMENT="** TAILSMAN DETECTED SECRETS IN PR. **\n\n $(cat tailsman_output.txt) \n"
          gh pr comment "$PR_URL" --body "$COMMENT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

